import Navbar from '@/app/components/navbar';
import './globals.css';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className='no-scrollbar'>
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
